from __future__ import annotations

from typing import TYPE_CHECKING, Protocol

if TYPE_CHECKING:
    from rag.results import CombinedSummaryResult, ParseResult, SectionSummaryResult, SummaryResult
    from rag.types import (
        ChunkRow,
        DocumentRow,
        FileType,
        ProcessingLogEntry,
        SearchFilters,
        SearchHit,
        SectionRow,
        SyncStateRow,
        VectorPoint,
    )


class Embedder(Protocol):
    def embed_batch(self, texts: list[str]) -> list[list[float]]: ...
    def embed_query(self, query: str) -> list[float]: ...
    @property
    def dimensions(self) -> int: ...
    @property
    def model_version(self) -> str: ...


class Summarizer(Protocol):
    def summarize_document(
        self, text: str, title: str | None, file_type: str
    ) -> SummaryResult: ...
    def summarize_section(
        self, text: str, heading: str | None, doc_context: str
    ) -> SectionSummaryResult: ...
    def summarize_combined(
        self,
        text: str,
        title: str | None,
        file_type: str,
        sections: list[tuple[str | None, str]],
    ) -> CombinedSummaryResult: ...
    @property
    def available(self) -> bool: ...


class MetadataDB(Protocol):
    def upsert_sync_state(self, state: SyncStateRow) -> None: ...
    def get_sync_state(self, file_path: str) -> SyncStateRow | None: ...
    def get_pending_files(self, limit: int) -> list[SyncStateRow]: ...
    def upsert_document(self, doc: DocumentRow) -> None: ...
    def get_document(self, doc_id: str) -> DocumentRow | None: ...
    def get_document_by_hash(self, content_hash: str) -> DocumentRow | None: ...
    def insert_sections(self, sections: list[SectionRow]) -> None: ...
    def get_sections(self, doc_id: str) -> list[SectionRow]: ...
    def insert_chunks(self, chunks: list[ChunkRow]) -> None: ...
    def get_chunks(self, doc_id: str) -> list[ChunkRow]: ...
    def get_chunk(self, chunk_id: str) -> ChunkRow | None: ...
    def get_adjacent_chunks(
        self, doc_id: str, chunk_order: int, window: int
    ) -> list[ChunkRow]: ...
    def get_chunks_by_section(self, section_id: str) -> list[ChunkRow]: ...
    def log_processing(self, entry: ProcessingLogEntry) -> None: ...
    def get_document_count(self) -> int: ...
    def get_chunk_count(self) -> int: ...
    def get_error_count(self) -> int: ...
    def get_recent_documents(
        self, limit: int, folder_filter: str | None = None
    ) -> list[DocumentRow]: ...
    def get_all_tracked_paths(self) -> list[str]: ...


class VectorStore(Protocol):
    def upsert_points(self, doc_id: str, points: list[VectorPoint]) -> None: ...
    def delete_stale_points(self, doc_id: str, keep_ids: set[str]) -> None: ...
    def query_dense(
        self,
        vector: list[float],
        filters: SearchFilters,
        limit: int,
        record_type: str | None = None,
    ) -> list[SearchHit]: ...
    def query_keyword(self, query: str, filters: SearchFilters, limit: int) -> list[SearchHit]: ...


class Reranker(Protocol):
    def rerank(self, query: str, candidates: list[SearchHit], top_k: int) -> list[SearchHit]: ...


class Parser(Protocol):
    def parse(
        self, file_path: str, ocr_enabled: bool, content_hash: str | None = None
    ) -> ParseResult: ...
    @property
    def supported_types(self) -> set[FileType]: ...
